### ISSUE TITLE
//fixlighting causes an Error

### ISSUE THREAD

**Issue by CookiieChris** [IntellectualSites/FastAsyncWorldEdit-1.13#287] opened 2019-12-17 22:30 UTC
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/88aa9b48ed4244c88679100e8abcfd2d

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Bukkit-Official(1.14-159;1e0e29b)

**[REQUIRED] Spigot/Paper Version Number:** 
see Debugpaste

**[REQUIRED] Description of the problem:**
//fixlighting causes an Error in the Console - No Lightchanges ingame

**How to replicate**:
Set Pos1 and Pos2
Execute //fixlighting

**Plugins being used on the server:**
see Debugpaste

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2019-12-19 17:17
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/99

**Comment by N0tMyFaultOG** [comment] 2019-12-19 17:18
Lightning is currently not implemented

**Closed by N0tMyFaultOG** 2019-12-19 17:17 UTC
Labels: Requires Testing
