### ISSUE TITLE
ClassNotFoundException: com.destroystokyo.paper.event.server.AsyncTabCompleteEvent

### ISSUE THREAD

**Issue by BeErikk** [IntellectualSites/FastAsyncWorldEdit-1.13#139] opened 2019-04-30 07:33 UTC
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

[09:15:27 INFO]: (FAWE) FastAsyncWorldEdit 1.13-19.4.29-ea07b54-104 by Empire92
[09:15:27 INFO]: ------------------------------------
[09:15:27 INFO]:  - DATE: Apr 29, 2019 12:00:00 AM
[09:15:27 INFO]:  - COMMIT: ea07b54
[09:15:27 INFO]:  - BUILD: 104
[09:15:27 INFO]:  - PLATFORM: bukkit
[09:15:27 INFO]: ------------------------------------
[09:15:27 INFO]: Platforms:
[09:15:27 INFO]:  - Bukkit (1.13.104)
[09:15:27 INFO]: Capabilities:
[09:15:27 INFO]:  - GAME_HOOKS: Bukkit
[09:15:27 INFO]:  - CONFIGURATION: Bukkit
[09:15:27 INFO]:  - USER_COMMANDS: Bukkit
[09:15:27 INFO]:  - PERMISSIONS: Bukkit
[09:15:27 INFO]:  - WORLDEDIT_CUI: Bukkit
[09:15:27 INFO]:  - WORLD_EDITING: Bukkit
[09:15:27 INFO]: ------------------------------------
[09:15:27 INFO]: Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki

**[REQUIRED] Spigot/Paper Version Number:** 

**Links to config.yml and config-legacy.yml file:** 

**[REQUIRED] Description of the problem:**

[09:11:01 WARN]: java.lang.ClassNotFoundException: com.destroystokyo.paper.event.server.AsyncTabCompleteEvent
[09:11:01 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[09:11:01 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136)
[09:11:01 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82)
[09:11:01 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[09:11:01 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[09:11:01 WARN]:        at java.lang.Class.forName0(Native Method)
[09:11:01 WARN]:        at java.lang.Class.forName(Unknown Source)
[09:11:01 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.lambda$new$0(FaweBukkit.java:138)
[09:11:01 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[09:11:01 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[09:11:01 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[09:11:01 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[09:11:01 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[09:11:01 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[09:11:01 WARN]:        at java.lang.Thread.run(Unknown Source)

**Plugins being used on the server:**

EssentialsX-2.16.1.150 LightCleaner-1.13.1-v1 Factions3 mcMMO

**How to replicate**:

start server with latest spigot and FastAsyncWorldEdit-bukkit-1.13.104.jar
server log:
[2019-04-30-1.log.gz](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/files/3130258/2019-04-30-1.log.gz)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

Are these just warnings for missing paper-spigot classes and can be ignored?

**Comment by N0tMyFaultOG** [comment] 2019-04-30 07:46
Duplicate of #133

**Closed by N0tMyFaultOG** 2019-04-30 07:46 UTC
