### ISSUE TITLE
IllegalArgumentException: Plugin already initialized!

### ISSUE THREAD

**Issue by BeErikk** [IntellectualSites/FastAsyncWorldEdit-1.13#131] opened 2019-04-22 22:51 UTC
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

>fawe debugpaste
[00:42:20 INFO]: (FAWE) There was an error handling a FAWE command: [See console]
[00:42:20 INFO]: java.net.ConnectException: Connection timed out: connect
[00:42:20 ERROR]: An unexpected error occurred while handling a FAWE command
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:?]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:?]
        at com.boydti.fawe.util.IncendoPaster.upload(IncendoPaster.java:127) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.boydti.fawe.util.IncendoPaster.debugPaste(IncendoPaster.java:233) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.command.WorldEditCommands.debugpaste(WorldEditCommands.java:117) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:266) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-1.13.87.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar:git-Spigot-f09662d-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f09662d-a46fdbc]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
>

**Description of the problem:**

During server initalisation the FastAsyncWorldEdit plugin throws exceptions. I add the server log
[2019-04-22-6.log.gz](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/files/3105113/2019-04-22-6.log.gz)

**How to replicate**:

Current Spigot and latest FastAsyncWorldEdit-1.13 (FastAsyncWorldEdit-bukkit-1.13.87)
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by mibby** [comment] 2019-04-23 12:30
Paper dev 624 (Spigot 1.13.2)
FAWE-Breaking dev 89
FAVS-Breaking dev 89
PlotSquared-Breaking dev 248
WorldGuard dev 1843

I also seem to be experiencing this since updating FAWE. :(

```
[05:28:38] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.rename(WorldEditPlugin.java:326)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.init(WorldEditPlugin.java:154)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:140)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:28:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:28:38] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331)
[05:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235)
[05:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[05:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[05:28:38] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:172)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:54)
[05:28:38] [Server thread/WARN]: 	at com.boydti.fawe.Blank.<init>(Blank.java:5)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:28:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:28:38] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[05:28:38] [Server thread/WARN]: 	... 17 more
[05:28:38] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:175)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:54)
[05:28:38] [Server thread/WARN]: 	at com.boydti.fawe.Blank.<init>(Blank.java:5)
[05:28:38] [Server thread/WARN]: 	... 13 more
[05:28:38] [Server thread/INFO]: [WorldEdit] Please restart the server if you have any plugins which depend on FAWE.
[05:28:38] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.rename(WorldEditPlugin.java:326)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java:166)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:190)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.init(WorldEditPlugin.java:156)
[05:28:38] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:140)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:28:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:28:38] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331)
[05:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235)
[05:28:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[05:28:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[05:28:38] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:172)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:54)
[05:28:38] [Server thread/WARN]: 	at com.boydti.fawe.Blank.<init>(Blank.java:5)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:28:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:28:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:28:38] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[05:28:38] [Server thread/WARN]: 	... 20 more
[05:28:38] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:175)
[05:28:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:54)
[05:28:38] [Server thread/WARN]: 	at com.boydti.fawe.Blank.<init>(Blank.java:5)
[05:28:38] [Server thread/WARN]: 	... 13 more
```

**Comment by mibby** [comment] 2019-04-23 12:42
@N0tMyFaultOG I believe it is caused by this commit. https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/f56460c9aca5d2d3832e3e9d642c4be6d08a9e14

I loaded an older DummyFawe.jar and start-up was fine.

**Comment by N0tMyFaultOG** [comment] 2019-04-23 12:56
> @N0tMyFaultOG I believe it is caused by this commit. [f56460c](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/f56460c9aca5d2d3832e3e9d642c4be6d08a9e14)
> 
> I loaded an older DummyFawe.jar and start-up was fine.

Yep, it is

**Comment by N0tMyFaultOG** [comment] 2019-04-23 13:39
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/02a6caa3ab77d0870dc3dc60cde039eb6d93c31a

**Closed by N0tMyFaultOG** 2019-04-23 13:39 UTC
Labels: Approved, [!] Bug

**Comment by BeErikk** [comment] 2019-04-24 17:57
Thanks for the swift fix. Sorry to ask but when will you try a new build? I'm eager to start editing :)
