### ISSUE TITLE
//set glitching surrounding chunks after server starts.

### ISSUE THREAD

**Issue by Epicnicity322** [IntellectualSites/FastAsyncWorldEdit-1.13#284] opened 2019-12-11 23:52 UTC
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
http://athion.net/ISPaster/paste/view/abebd3b6e8e14de3a6b89cb3d9a04cea

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
&7FastAsyncWorldEdit-159 created by Empire92
&7FAWE version:
- Date Dec 11, 2019 12:00:00 AM
- Commit fe1f1d65
- Build 159
- Platform bukkit
&7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.14-159;1e0e29b)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-235 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-233 (MC: 1.14.4)
You are 1 version(s) behind

**[REQUIRED] Description of the problem:**
I was testing some things on my server, when I wanted to add some farmland. So I selected a small region and used //set farmland when suddenly a giant hole appeared in its surroundings. I don't know why this happened, probably because I updated to the latest version of fawe 1.14 in jenkins earlier. I just filled the area with some grass with //set 2 and it worked fine. Then I used set again and nothing happened. When I restarted the server and used //set again, the issue happened again.
Here are some screens I took:
https://prnt.sc/q9kwyv
https://prnt.sc/q9kx6v
With light fixed:
https://prnt.sc/q9kwfk
https://prnt.sc/q9kxrz

And the errors found in my console are probably by a glitched beacon plugin I was testing. Fawe didn't generate any errors.

**How to replicate**:
- Start your server
- Select a small region
- Use //set farmland

**Plugins being used on the server:**
Plugins (77): AdminFun*, AntiVPN, AuthMe, Autorank, BeaconPlus2*, BetterChairs*, BKCommonLib, BlocksHub, ChestShop, ChickenGlide, Citizens, Coins*, ColoredTags*, ConsoleSpamFix, CoreProtect, CrazyCrates, CustomPolls*, DangerousCaves, DangerousNether*, DeadSouls, DeathMessagesPrime, Elevator, EnderPearlFix, EntityTrackerFixer, EpicPluginAPI, EpicWorldGenerator, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FastLogin, HackedCore*, HackedServer*, HolographicDisplays, IllegalStack, InventoryRollback, ItemEditor, JukeBox, Lasso, LightCleaner, LimitPillagers, LuckPerms, Magma, Matrix, mcMMO, Multiverse-Core, MyCommand, NoteBlockAPI, OpenInv, PearlRider, PlaceholderAPI, PlayMoreSounds, PluginConstructorAPI, PluginLibrary, PlugMan, ProtocolLib, PvPManager, RandomTeleport, RedProtect, Revenge, SexyMotd*, SmoothSleep, SnowierSnow, SuddenDeath, SuperVanish, SwimmingHorses, TabList, UltimateChat, UltimateTimber, UpdatedSpawners, Vault, ViaVersion*, VillagerOptimiser, Votifier, VotingPlugin, WorldBorder, WorldEdit, XWeather

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2019-12-19 17:19
Update Fawe, I cannot reproduce the issue based on the given information

**Comment by N0tMyFaultOG** [comment] 2019-12-19 17:23
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/269

**Closed by N0tMyFaultOG** 2019-12-19 17:23 UTC
Labels: Requires Testing
