### ISSUE TITLE
//stack does  not work

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#22] opened 2019-01-16 18:06 UTC
//stack does nothing. It prints the message saying x blocks changed.
But no changes happen in world.

using @IronApollo 's vector update

**Comment by RealmportalMC** [comment] 2019-02-02 20:38
I couldnt get it working with anything.

I just noticed it says INFO: (FAWE) "Invalid entity minecraft:player"

**Comment by N0tMyFaultOG** [comment] 2019-02-02 20:58
>I just noticed it says INFO: (FAWE) "Invalid entity minecraft:player"

That is a known issue being worked on

**Comment by RealmportalMC** [comment] 2019-02-02 22:20
Alright. Hopefully it fixes //stack

**Comment by adamlaughlin** [comment] 2019-02-06 17:18
> I just noticed it says INFO: (FAWE) "Invalid entity minecraft:player"
Try making sure you aren't within the boundaries of your selection when copying or stacking until the relevant patches hit.  Maybe that's why I am having success.

**Comment by RealmportalMC** [comment] 2019-02-06 18:46
> 
> 
> > I just noticed it says INFO: (FAWE) "Invalid entity minecraft:player"
> 
> Try making sure you aren't within the boundaries of your selection when copying or stacking until the relevant patches hit. Maybe that's why I am having success.

It didnt seem to matter. i placed 1 block infront of me.  select only thbat1  block. stack it facing away from me and it happens. (i was like 8 blocks away doing //stack 1

**Comment by SirYwell** [comment] 2019-03-20 23:44
Works for me in the current version with old blocks, new blocks and stairs and fluids.

**Comment by AeSix** [comment] 2019-03-21 00:46
I can confirm //stack works for me for all blocks I tested, all of what SirYWell stated, as well as signs.  HOWEVER signs do not duplicate content.  This is part of a separate issue however.

**Comment by N0tMyFaultOG** [comment] 2019-04-20 21:27
Fixed in latest fawe-breaking

**Closed by N0tMyFaultOG** 2019-04-20 21:27 UTC
Labels: Requires Testing
