### ISSUE TITLE
Using "connected blocks" such as fence or iron bars results in non-connected blocks.

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#18] opened 2019-01-16 16:40 UTC
Red and blue are my pos1 and pos2

i did //replace air oak_fence

this is the result: 
![2019-01-16_10 38 58](https://user-images.githubusercontent.com/22693741/51264021-1e356b80-197b-11e9-8a09-594a75245971.png)

**Comment by RealmportalMC** [comment] 2019-01-16 16:42
Viaversion had an issue regardng the way connceted locks are handled as of 1.13

https://github.com/MylesIsCool/ViaVersion/issues/856

**Comment by RealmportalMC** [comment] 2019-01-16 16:44
seems to be the same issue as https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/13

**Comment by RealmportalMC** [comment] 2019-01-16 18:01
using @IronApollo's version for testing

**Comment by Germanode** [comment] 2019-02-21 22:09
Happening with tall grass too. 1.12.2 Tall grass appears as grass and a flower on top on 1.13.2.

**Comment by k9lego** [comment] 2019-02-26 20:50
Still having that issue with fence posts on a 1.8.8 PaperSpigot server... On 1.13.2 fence posts don't properly connect

**Comment by AeSix** [comment] 2019-03-21 01:22
This is a duplicate of #13 (same issue, this ticket is however a little more apt to the entire problem)
This issue affects all connected blocks (fence, wall, glass panes, rails, chest(?))

As mentioned above, this issue is probably due to block connections now being handled by the server, as stated here:
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/13#issuecomment-475082347

**Closed** 2019-11-23 19:00 UTC
Labels: Approved, Fixed (commanding), [!] Bug
