### ISSUE TITLE
Schematic load/paste error

### ISSUE THREAD

**Issue by stuvanya** [IntellectualSites/FastAsyncWorldEdit-1.13#282] opened 2019-12-08 10:34 UTC
# Bug report for FastAsyncWorldEdit 1.14.4
I used last version of FAWE (1.14-152), PaperSpigot 1.14.4. I have copied territory and saved it in schematic, then I load this schematic and paste.
Original region:
![Снимок экрана от 2019-12-08 13-33-37](https://user-images.githubusercontent.com/11257143/70388186-5c86af80-19bf-11ea-931c-8c535f877dea.png)
Pasted:
![Снимок экрана от 2019-12-08 13-31-51](https://user-images.githubusercontent.com/11257143/70388190-63adbd80-19bf-11ea-9bb6-e9552aa164fb.png)

**Comment by N0tMyFaultOG** [comment] 2019-12-19 17:21
Can you upload the schematic please? It appears to work fine for me.

**Comment by stuvanya** [comment] 2019-12-19 19:38
[sss2.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/files/3985352/sss2.zip)

**Comment by SaltyAimbOtter** [comment] 2019-12-21 19:17
I can confirm this. I get additional sea lanterns in my //paste. There are none at all in the building.
https://cdn.discordapp.com/attachments/344128526435221505/658020992941162497/unknown.png
Schematic:
https://send.firefox.com/download/d99273ab150ffbd8/#kZFf9SEyulm7ImVSP4FUjg

**Comment by Rixafy** [comment] 2019-12-26 00:03
I have the same problem, it happens only on bigger/more complex schematic, if you copy few blocks of stone it's okay, but larger map or island will end like this.

**Comment by N0tMyFaultOG** [comment] 2019-12-30 17:55
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/264

**Comment by N0tMyFaultOG** [comment] 2019-12-30 17:56
Schematics seem to not work properly set, I'll just link this issue with similar clipboard issues.

**Closed by N0tMyFaultOG** 2019-12-30 17:55 UTC
Labels: Approved, [!] Bug

**Comment by Rixafy** [comment] 2019-12-30 17:58
Ok, but when I copy it to clipboard and paste, it works, if I save it as a schematic, load and paste, it's broken exactly like in screenshots (random blocks like stairs).
