### ISSUE TITLE
Entity copy and pasting doesnt work

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#24] opened 2019-01-16 18:10 UTC
copy to clipboard (with entities)

//paste
entites dont copy.

Using @IronApollo s vector update

**Comment by AeSix** [comment] 2019-03-21 01:52
I can confirm this is still an issue with FAWE-NVS 165
Tested with parrots and minecarts.
Both copy/paste and //stack fail to duplicate the entities.

**Comment by Tsoccerguy3** [comment] 2019-06-21 20:05
confirmed , still issue with FAWE breaking build 144

**Comment by N0tMyFaultOG** [comment] 2019-11-23 19:26
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/71

**Closed by N0tMyFaultOG** 2019-11-23 19:26 UTC
Labels: Approved, [!] Bug
