### ISSUE TITLE
Set ignores height boundary 

### ISSUE THREAD

**Issue by janLindner** [IntellectualSites/FastAsyncWorldEdit-1.13#262] opened 2019-11-23 22:55 UTC
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-132

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-226 (MC: 1.14.4)

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/sNuReqMv
https://pastebin.com/tVyApQB5

**[REQUIRED] Description of the problem:**
When filling a selection with `//set 1` the height boundary is ignored. The selection seems to be virtually expanded to the next upper chunk section border. This also only occures when a chunk section border is within the selection. See example below:

Selecting the first position:
![2019-11-23_23 46 07](https://user-images.githubusercontent.com/18546571/69486403-a615bd00-0e4b-11ea-9298-d1b4e377d542.png)

Selecting the second position in the next chunk section:
![2019-11-23_23 46 20](https://user-images.githubusercontent.com/18546571/69486406-af9f2500-0e4b-11ea-8185-13a48d681bc5.png)

Placing the blocks with `//set 1` Result: The blocks are placed up to the chunk section border
![2019-11-23_23 46 57](https://user-images.githubusercontent.com/18546571/69486412-c776a900-0e4b-11ea-87a6-0991ff32360c.png)

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, ProtocolLib

**How to replicate**:
Select an area any size that reaches over a chunk section. Place blocks with the `//set` Command.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2019-11-23 22:56
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/261
(Issues are different, behavior is the same)

**Closed by N0tMyFaultOG** 2019-11-23 22:56 UTC
Labels: Requires Testing
