### ISSUE TITLE
Rotating container blocks results in cleared inventories

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/FastAsyncWorldEdit-1.13#147] opened 2019-05-16 02:04 UTC
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[03:58:17 INFO]: [FAWE] FastAsyncWorldEdit-1.13-110 by Empire92
[03:58:17 INFO]: ------------------------------------
[03:58:17 INFO]:  - DATE: May 12, 2019 12:00:00 AM
[03:58:17 INFO]:  - COMMIT: e72a5cf
[03:58:17 INFO]:  - BUILD: 110
[03:58:17 INFO]:  - PLATFORM: bukkit
[03:58:17 INFO]: ------------------------------------
[03:58:17 INFO]: Platforms:
[03:58:17 INFO]:  - Bukkit
[03:58:17 INFO]: Capabilities:
[03:58:17 INFO]:  - GAME_HOOKS: Bukkit
[03:58:17 INFO]:  - CONFIGURATION: Bukkit
[03:58:17 INFO]:  - USER_COMMANDS: Bukkit
[03:58:17 INFO]:  - PERMISSIONS: Bukkit
[03:58:17 INFO]:  - WORLDEDIT_CUI: Bukkit
[03:58:17 INFO]:  - WORLD_EDITING: Bukkit
[03:58:17 INFO]: ------------------------------------
```

**[REQUIRED] Spigot/Paper Version Number:** 

`CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**Links to config.yml and config-legacy.yml file:** 

config.yml: https://hastebin.com/omelusogen.yml
config-legacy.yml: https://hastebin.com/ewenosuciv.yml

**[REQUIRED] Description of the problem:**

Copying, rotating, then pasting container blocks results in cleared inventories. Tested with droppers, hoppers, dispensers, and furnaces.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment] 2019-06-08 15:02
The same related issue with chest and sign data
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/132#issue-436216199

**Comment by N0tMyFaultOG** [comment] 2019-06-19 14:42
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/132

**Closed by N0tMyFaultOG** 2019-06-19 14:42 UTC
