### ISSUE TITLE
//smooth -s doesn't work

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit-1.13#205] opened 2019-08-06 15:27 UTC
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
WorldEdit v1.13.177

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-638 (MC: 1.13.2)

**Links to config.yml and config-legacy.yml file:** 
config.yml: https://brew.brdv.coffee/alapidojuy.hs
config-legacy.yml: https://brew.brdv.coffee/qunigolaja.hs

**[REQUIRED] Description of the problem:**
Using //smooth -s doesn't smooth snow terrain using the partial layers of snow.
Works correctly on 1.12.2 version of FAWE:
https://brdv.coffee/storage/uploads/4/QtMkRk8xam23.png

Does not work with 1.13.2 version of FAWE:
https://brdv.coffee/storage/uploads/4/vbSCAWgd09Is.png

**Plugins being used on the server:**
FAWE/P2 with `worlds: true`

**How to replicate**:
Make terrain with snow blocks, use //smooth -s and it doesn't work as intended with the snow meta.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2019-11-23 19:20
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/166

**Closed by N0tMyFaultOG** 2019-11-23 19:20 UTC
Labels: [✖] Duplicate
