### ISSUE TITLE
Pasting rotated clipboard doesnt work

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#23] opened 2019-01-16 18:08 UTC
copy something to clipboard//rotate 90 and //paste

nothing pastes.

using @IronApollo 's vector update

**Comment by RealmportalMC** [comment] 2019-01-17 01:19
Nor does cipboard after //flip

**Comment by SirYwell** [comment] 2019-03-20 13:31
Using the current version (165), rotating works fine

**Comment by AeSix** [comment] 2019-03-21 00:43
I can confirm that *dumb* block rotation and flip work.  
However, signs, chests, banners, heads, etc are not pasting (separate issue)  Signs rotate, but lose text. Similar for other items. 

***Important versions:***
[20:24:54 INFO]: This server is running Paper version git-Paper-517 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

[20:24:56 INFO]: PlotSquared version 4.189
[20:24:56 INFO]: Easy, yet powerful Plot World generation and management.
[20:24:56 INFO]: Authors: Citymonstret, Empire92, MattBDev and dordsor21

[20:24:59 INFO]: FastAsyncWorldEdit version 1.0
[20:25:02 INFO]: moreMandMs issued server command: /token shop
[20:25:02 INFO]: [PrimeTokens] Getting token count for a8837bb3-6c2c-41ad-a73f-381fba4bd3ba. They have: 14

[20:25:06 INFO]: WorldEdit version unspecified
[20:25:06 INFO]: Fast Async WorldEdit plugin
[20:25:06 INFO]: Author: Empire92

@RealmportalMC  As this issue is resolved in the code that is working towards release, once it's out if you still have an issue, please create a new /fawe debugpaste and update the ticket.  The ticket may be closed (I can't do it, just a tester)  I know it sucks having to wait so long, but I think patience will be worth it in the end :)

**Comment by MattBDev** [comment] 2019-03-21 01:13
I wasn't able to reproduce this issue.

**Comment by Tsoccerguy3** [comment] 2019-03-23 21:05
as suggested , i compiled  from the dev branches , new-vector-system and new-vector-system2 , 

tested builds 
FastAsyncWorldEdit-bukkit-1.13.167
and
FastAsyncWorldEdit-bukkit-1.13.168

Rotation of stairs works

//flip in any direcion is 100 percent broken 

![2019-03-23_16 49 30](https://user-images.githubusercontent.com/22108822/54871623-978f7700-4d8d-11e9-9ea5-a4a3a1c6a49e.png)
![2019-03-23_16 51 13](https://user-images.githubusercontent.com/22108822/54871624-978f7700-4d8d-11e9-891e-e10c159dc601.png)

**Comment by MattBDev** [comment] 2019-03-24 02:14
@Tsoccerguy3 thanks for testing. Helps us narrow it down.  😊

**Comment by Tsoccerguy3** [comment] 2019-03-25 12:29
A note , the stair corners are not flipped , but the North , South , East and West stairs are flipped correctly . I can not find anything in the new code that handles specifically the stair corner ID's , //flip up , does nothing and again i don't see any code added to handle this instance . It's in Worldedit , but not in FAWE

**Comment by Tsoccerguy3** [comment] 2019-03-25 22:39
![2019-03-25_18 31 26](https://user-images.githubusercontent.com/22108822/54958765-43bb9400-4f2d-11e9-87c3-fb24b3e67d4a.png)

**Comment by Tsoccerguy3** [comment] 2019-03-25 22:40
In the picture above you can see what blocks were given the wrong ID's in the flip

**Comment by Tsoccerguy3** [comment] 2019-03-25 22:48
> 
> 
> @Tsoccerguy3 thanks for testing. Helps us narrow it down. 😊

I created a test flip from a variety of stairs , it appears that a corner ID is not being calculated correctly. It is a big problem is a build has a lot of stair types in the build . try fixing by hand after a flip , you never get all the incorrectly flipped stairs during a fix

**Comment by Tsoccerguy3** [comment] 2019-03-26 16:37
Where to start , look in WorldEdit Core at Block Data.java

Look at flip stair section . looks like the cases are wrong

**Comment by Tsoccerguy3** [comment] 2019-03-27 05:08
I also could not find any code related to //flip up or //flip down , in spigot these commands do nothing

**Comment by Tsoccerguy3** [comment] 2019-04-03 13:10
I would think that this //flip bug would be a priority , its important to be able the mirror sections of a build , and if there are lots of stair corners it's just to time consuming to manually fix .

**Comment by Tsoccerguy3** [comment] 2019-04-07 18:36
![2019-04-07_14 24 50](https://user-images.githubusercontent.com/22108822/55688065-4f9e5180-5942-11e9-911d-5a57e7ae571c.png)
//rotate and //flip are fixed , please close

**Closed** 2019-04-07 19:07 UTC
Labels: Requires Testing
