### ISSUE TITLE
Glass pane isn't connected to each other

### ISSUE THREAD

**Issue by JokerLiuPro** [IntellectualSites/FastAsyncWorldEdit-1.13#156] opened 2019-05-25 17:55 UTC
# Bug report for FastAsyncWorldEdit 1.13.2
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[01:41:12] [Craft Scheduler Thread - 70/INFO]: (FAWE) FastAsyncWorldEdit-1.13-113 by Empire92
[01:41:12] [Craft Scheduler Thread - 70/INFO]: ------------------------------------
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - DATE: 2019年5月24日 上午12:00:00
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - COMMIT: 3eec877
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - BUILD: 113
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - PLATFORM: bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]: ------------------------------------
[01:41:12] [Craft Scheduler Thread - 70/INFO]: Platforms:
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]: Capabilities:
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - GAME_HOOKS: Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - CONFIGURATION: Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - USER_COMMANDS: Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - PERMISSIONS: Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - WORLDEDIT_CUI: Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]:  - WORLD_EDITING: Bukkit
[01:41:12] [Craft Scheduler Thread - 70/INFO]: ------------------------------------
[01:41:12] [Craft Scheduler Thread - 70/INFO]: Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki

**[REQUIRED] Spigot/Paper Version Number:** 
[01:41:43] [Server thread/INFO]: --------------------------------------------------
[01:41:43] [Server thread/INFO]: CMI Version: 8.6.3.2-> 8.6.4.0
[01:41:43] [Server thread/INFO]: Server Version: Paper(626) 1.13.2-R0.1-SNAPSHOT
[01:41:43] [Server thread/INFO]: Vault Version: 1.6.11(+)
[01:41:43] [Server thread/INFO]: --------------------------------------------------

**Links to config.yml and config-legacy.yml file:** 
config.yml:
https://pastebin.com/dMCwTYUK
config-legacy.yml:
https://pastebin.com/U554vgRF

**[REQUIRED] Description of the problem:**
Glass pane isn't connected to each other when i do //set minecraft:black_stained_glass_pane
https://media.discordapp.net/attachments/344128526435221505/581896470853320720/unknown.png?width=960&height=556

**Plugins being used on the server:**
Plugins (40): Arceon, BlocksHub, BossShopPro, BuildersUtilities, BuycraftX, ChatControl, Citizens, CitizensCMD, ClearLag*, CMI, CoreProtect, CraftBook, Emotes, eZProtector, FastAsyncVoxelSniper, FastAsyncWorldEdit, goBrush, goPaint, GuiShopManager*, HeadDatabase*, HolographicDisplays, ItemJoin, LibsDisguises, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, NametagEdit*, PlaceholderAPI*, PlotSquared, PlugMan, ProtocolLib*, SelectionVisualizer, Tab*, TreysCommandBlocker*, Vault*, VoidGenerator, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**How to replicate**:
1. pos 2 point 
2. //set minecraft:black_stained_glass_pane

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment] 2019-05-26 02:13
fuzzy block issue , incomplete code . Is being worked on
affects:

glass panes
iron bars
fences 
red stone
etc ..

**Comment by Tsoccerguy3** [comment] 2019-05-31 20:08
Any luck getting the fuzzy block code finished and name matching done .
fixing this fixes about 6 issues from what i can see , in the issues posted

**Comment by Tsoccerguy3** [comment] 2019-06-02 16:18
you have to use the new name structure to do //set material

example : 
//set minecraft:black_stained_glass_pane[north=true,south=true,east=false,west=false]

in the statement change the true or false to turn of the fork state

**Comment by MattBDev** [comment] 2019-06-10 15:54
Duplicate of #18

**Closed** 2019-06-10 15:55 UTC
Labels: Approved, Priority, [!] Bug
