### ISSUE TITLE
WorldGuard API patchy

### ISSUE THREAD

**Issue by xXSchrandXx** [IntellectualSites/FastAsyncWorldEdit-1.13#74] opened 2019-03-22 11:00 UTC
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://hastebin.com/awezojulov

**Description of the problem:**
I can't use the [RegionAPI](http://worldguard.enginehub.org/en/latest/developer/regions/flag-calculation/) from WorldGuard.
``` LOG
[11:56:32] [Server thread/ERROR]: Error occurred while enabling Ragebears v0.0 (Is it up to date?)
java.lang.Error: Unresolved compilation problems: 
	The type com.sk89q.worldedit.world.World cannot be resolved. It is indirectly referenced from required .class files
	The method get(World) from the type RegionContainer refers to the missing type World
	The type com.sk89q.worldedit.Vector cannot be resolved. It is indirectly referenced from required .class files
	The method getApplicableRegions(Vector) from the type RegionManager refers to the missing type Vector
	SERVER cannot be resolved or is not a field

	at bukkit.listener.WGServerTP.<init>(WGServerTP.java:27) ~[?:?]
	at bukkit.main.onEnable(main.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-570]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-570]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**How to replicate**:
``` JAVA
22.  @EventHandler
23.  public void onMove(PlayerMoveEvent e) {
24.    Player p = e.getPlayer();
25.    Location loc = e.getTo();
26.    RegionContainer container = WorldGuard.getInstance().getPlatform().getRegionContainer();
27.    RegionManager regions = container.get(loc.getWorld());
28.    ApplicableRegionSet set = regions.getApplicableRegions(loc.toVector());
29.    String server = set.queryValue(p, Flags.SERVER);
30.    if (server != null) {
31.      bungeecord.connectToBungeeServer(p, server);
32.    }
33.  }
```

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment] 2019-03-22 11:14
Does this issue occur when using the latest release of WorldEdit?

**Comment by xXSchrandXx** [comment] 2019-03-22 11:15
> Does this issue occur when using the latest release of WorldEdit?

[FAWE](https://empcraft.com/fawe/download/)
or
[WE](http://wiki.sk89q.com/wiki/WorldEdit)

**Comment by IronApollo** [comment] 2019-03-22 11:21
Well let me back up for a second.

It's important to remember that the currently released 1.13 version of FAWE is massively behind API compatibility with upstream WorldEdit's. If you're trying to use the current 1.13 FAWE-API with latest releases of WorldGuard, it will definitely not work in part due to the changes in Vectors, as well as several other API changes. 

If this is not the case for you (you're using an API-compatible release of WorldGuard with FAWE's), please clarify.

**Comment by xXSchrandXx** [comment] 2019-03-22 11:32
I am using ther WorldGuard version linked in the https://empcraft.com/fawe/download/ website.

**Comment by xXSchrandXx** [comment] 2019-03-22 11:42
Or as simple as the question can be, can I create and use custom RegionFlags?

**Comment by Tsoccerguy3** [comment] 2019-06-21 20:17
Same issue posted here , a little more information
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/142#issue-441929901

**Comment by MattBDev** [comment] 2019-10-13 01:33
Duplicate of #142

**Closed by MattBDev** 2019-10-13 01:33 UTC
Labels: Approved, Priority
