### ISSUE TITLE
Craftscripts doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit-1.13#170] opened 2019-06-08 13:48 UTC
Craftscripts doesn't work with version 1.13.2, with version 1.12.2 everything ran well. 
I have placed the scripts under _/plugins/FastAsyncWorldEdit/craftscripts_. But it says that I am missing a script engine (https://imgur.com/a/bZnMrEm): So I tried to install the js.jar from the rhino stuff and got the following error message: 
```
Could not load 'plugins\js.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
```
NotMyFault said that the issue on startup could be neglected since it's not a plugin.  Unfortunately the rhino stuff didn't helped: It is still missing the script engine and I can't use any craftscripts.

FAWE 1.13.128
Paper 1.13.2 - 628

**Comment by N0tMyFaultOG** [comment] 2019-06-08 15:03
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/46

**Closed by N0tMyFaultOG** 2019-06-08 15:03 UTC
Labels: Requires Testing
