### ISSUE TITLE
//copy not pasting all blocks

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [IntellectualSites/FastAsyncWorldEdit-1.13#102] opened 2019-04-06 19:05 UTC
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

https://incendo.org/paste/view/3b19844444c9490ca519ab593af690a0
**Description of the problem:**

When im copying this or other blocks only a few are beeing pasted:
Copied: http://prntscr.com/n8f6o9
Pasted: http://prntscr.com/n8f6zz
As you can see - blocks inside were not pasted

**How to replicate**:

Just //copy and //paste on newest FAWE
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment] 2019-04-06 19:10
I think this is a duplicate of #90 / #93

**Closed by SirYwell** 2019-04-06 19:10 UTC
